// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApp.DataAccess.Data;

#nullable disable

namespace MoviesApp.DataAccess.Migrations
{
    [DbContext(typeof(MoviesAppDbContext))]
    [Migration("20230830163221_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MoviesApp.Domain.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "First Movie, Yay!",
                            Genre = 2,
                            Title = "Action Movie",
                            Year = 1994
                        },
                        new
                        {
                            Id = 2,
                            Description = "Second Movie, Yay!",
                            Genre = 3,
                            Title = "Thriller Movie",
                            Year = 1999
                        },
                        new
                        {
                            Id = 3,
                            Description = "Third Movie, Yay!",
                            Genre = 2,
                            Title = "Better Action Movie",
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            Description = "Last Movie, Yay!",
                            Genre = 1,
                            Title = "Comedy Movie",
                            Year = 1899
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
